Repository mozilla-ai/agent-factory, pull requests merged in 2025-08, with the labels that each got.

#199 Scripts to test mcp servers and update doc from github actions
  .github/workflows/mcp-tests.yaml
  .gitignore
  Makefile
  docs/mcp-servers.json
  docs/mcp-servers.md
  docs/scripts/__init__.py
  docs/scripts/generate_mcp_table.py
  docs/scripts/test_mcp_servers.py
Labels: documentation, infra

#197 Agent uses mcpd binary to execute the tools search
  .gitignore
  Dockerfile
  Makefile
  README.md
  src/agent_factory/__main__.py
  src/agent_factory/factory_tools.py
  src/agent_factory/utils/io_utils.py
  tests/tools/test_search_mcp_servers.py
Labels: MCP

#211 feat: outputs include a file with agent's input parameters
  README.md
  docs/mcp-servers.md
  src/agent_factory/schemas.py
  src/agent_factory/utils/io_utils.py
  tests/generation/test_single_turn_generation.py
  tests/unit/test_io_utils.py
Labels: back-end

#181 Make max_attempts and min_successes configurable for CI generation tests
  tests/conftest.py
  tests/generation/test_single_turn_generation.py
  tests/generation/use_cases.yaml
  tests/utils/non_deterministic_runs.py
Labels: testing

#222 docs: initial content, automated doc build
  .github/workflows/docs.yml
  .github/workflows/mcp-tests.yaml
  Makefile
  docs/getting-started/installation.md
  docs/index.md
  docs/scripts/generate_mcp_table.py
  docs/user-guide/mcp-servers-template.md
  docs/user-guide/mcp-servers.md
  mkdocs.yml
Labels: documentation

#276 Update Criteria & Judge Agents arg variables
  eval/generate_evaluation_case.py
  eval/run_generated_agent_evaluation.py
  tests/generated_agent_evaluation/test_run_agent_evaluation.py
Labels: enhancement

#255 Improve docs
  README.md
  docs/getting-started/installation.md
  docs/getting-started/multi-turn-conversations.md
  docs/getting-started/usage.md
  docs/index.md
  mkdocs.yml
Labels: documentation
